name: 'Rust Toolchain'
description: 'Install the Rust toolchain (forwarding proxy)'
author: 'common-actions'

inputs:
  toolchain:
    description: 'Rust toolchain specification -- see https://rust-lang.github.io/rustup/concepts/toolchains.html#toolchain-specification'
    required: true

outputs:
  cachekey:
    description: 'A short hash of the rustc version, appropriate for use as a cache key.'
    value: ${{ steps.setup.outputs.cachekey }}
  name:
    description: "Rustup's name for the selected version of the toolchain."
    value: ${{ steps.setup.outputs.name }}

runs:
  using: 'composite'
  steps:
    - id: setup
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}

branding:
  icon: 'activity'
  color: 'purple'
