name: 'Docker Setup Buildx'
description: 'Set up Docker Buildx (forwarding proxy)'
author: 'common-actions'

outputs:
  name:
    description: 'Builder name'
    value: ${{ steps.setup.outputs.name }}
  driver:
    description: 'Builder driver'
    value: ${{ steps.setup.outputs.driver }}
  platforms:
    description: 'Builder node platforms'
    value: ${{ steps.setup.outputs.platforms }}

runs:
  using: 'composite'
  steps:
    - id: setup
      uses: docker/setup-buildx-action@v4.1.0

branding:
  icon: 'anchor'
  color: 'blue'
