name: 'Setup Node.js'
description: 'Setup a Node.js environment (forwarding proxy)'
author: 'common-actions'

inputs:
  node-version:
    description: "Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0."
    default: 24
  cache:
    description: 'Used to specify a package manager for caching. Supported values: npm, yarn, pnpm.'
    defualt: 'pnpm'

outputs:
  cache-hit:
    description: 'A boolean value to indicate if a cache was hit.'
    value: ${{ steps.setup.outputs.cache-hit }}
  node-version:
    description: 'The installed node version.'
    value: ${{ steps.setup.outputs.node-version }}

runs:
  using: 'composite'
  steps:
    - id: setup
      uses: actions/setup-node@v6.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

branding:
  icon: 'package'
  color: 'green'
